import {
  BountyContract,
  GameState,
  ItemDefinition,
  ItemId,
  MarketEvent,
  Mercenary,
  RouteEdge,
  SettlementDefinition,
  SettlementId,
  TransportDefinition,
  TransportId,
  RovingEntity,
  SecretLocation,
} from "./types";

export const ITEMS: Record<ItemId, ItemDefinition> = {
  water: {
    id: "water",
    name: "Purified Water (1L)",
    category: "survival",
    weightKg: 1.0,
    basePrice: 8,
    description:
      "Essential drinking water for humans and pack animals. Scarce in mining camps and desert rigs.",
  },
  food_rations: {
    id: "food_rations",
    name: "Dry Corn & Rations",
    category: "survival",
    weightKg: 0.8,
    basePrice: 12,
    description:
      "Preserved cornmeal and hardtack that keeps travelers alive on the sun-bleached trails.",
  },
  animal_forage: {
    id: "animal_forage",
    name: "Dry Hay & Forage",
    category: "survival",
    weightKg: 1.5,
    basePrice: 5,
    description:
      "Bundled scrub grass and oats for donkeys, mules, horses, and oxen. Cheap in farming and ranch towns.",
  },
  gasoline: {
    id: "gasoline",
    name: "Refined Gasoline (1L)",
    category: "survival",
    weightKg: 0.9,
    basePrice: 38,
    description:
      "Liquid gold of the wasteland. Pumped at Blackwater Rig and burned by motorcycles, buggies, and V8 trucks.",
  },
  raw_leather: {
    id: "raw_leather",
    name: "Cured Brahmin Leather",
    category: "commodity",
    weightKg: 2.5,
    basePrice: 45,
    description:
      "Thick hides tanned in Deadwood Gulch and Tombstone Crossing. Prized by tailors and armorers in Saint Louis.",
  },
  smoked_jerky: {
    id: "smoked_jerky",
    name: "Smoked Trail Jerky (Crate)",
    category: "commodity",
    weightKg: 2.0,
    basePrice: 34,
    description:
      "Salted meat cured over mesquite smoke. Miners and city guards pay a premium for real protein.",
  },
  scrap_metal: {
    id: "scrap_metal",
    name: "Salvaged Steel Ingots",
    category: "commodity",
    weightKg: 4.0,
    basePrice: 30,
    description:
      "Heavy smelted scrap from Leadville Shaft. Essential for New Denver, Saint Louis, and New Chicago workshops.",
  },
  salt: {
    id: "salt",
    name: "Desert Salt Sack",
    category: "commodity",
    weightKg: 2.0,
    basePrice: 22,
    description:
      "Used by ranchers in Deadwood Gulch and Tombstone Crossing to cure meat and hides without refrigeration.",
  },
  tools: {
    id: "tools",
    name: "Machinist Toolset",
    category: "commodity",
    weightKg: 3.0,
    basePrice: 75,
    description:
      "Precision wrenches and drills forged in New Denver and New Chicago. Frontier settlements pay top dollar.",
  },
  antibiotics: {
    id: "antibiotics",
    name: "Pre-War Antibiotics",
    category: "medical",
    weightKg: 0.3,
    basePrice: 115,
    description:
      "Synthesized in Saint Louis laboratories. High value-to-weight ratio for frontier clinics.",
  },
  luxury_cigars: {
    id: "luxury_cigars",
    name: "Saint Louis Reserve Cigars",
    category: "commodity",
    weightKg: 0.5,
    basePrice: 95,
    description:
      "Hand-rolled riverfront tobacco leaf for wealthy industrial barons and oil bosses.",
  },
  moonshine: {
    id: "moonshine",
    name: "Canyon Moonshine Jug",
    category: "contraband",
    weightKg: 1.8,
    basePrice: 68,
    isContraband: true,
    description:
      "Illicit high-proof liquor. Prohibited by checkpoints in Saint Louis, New Denver, and New Chicago, where it sells for huge profits.",
  },
  field_bandage: {
    id: "field_bandage",
    name: "Sterile Field Bandage",
    category: "medical",
    weightKg: 0.2,
    basePrice: 28,
    description:
      "Restores +30 HP in tactical combat (costs 3 AP) or patches wounds on the trail.",
  },
  copper_ore: {
    id: "copper_ore",
    name: "Smelted Copper Ore",
    category: "commodity",
    weightKg: 3.5,
    basePrice: 36,
    description:
      "High-grade copper ingots mined in Leadville Shaft. Essential for brass shell casings and metropolitan power grids.",
  },
  canned_beef: {
    id: "canned_beef",
    name: "Stockyard Canned Beef",
    category: "commodity",
    weightKg: 1.4,
    basePrice: 42,
    description:
      "Hermetically sealed tins of prime spiced beef packed in Tombstone Crossing. Sought after by miners and city garrisons.",
  },
  whiskey_barrel: {
    id: "whiskey_barrel",
    name: "Frontier Oak Whiskey Cask",
    category: "commodity",
    weightKg: 3.2,
    basePrice: 64,
    description:
      "Licensed aged bourbon from Deadwood and Tombstone distilleries. Legal everywhere and prized in northern rail hubs.",
  },
  diesel_parts: {
    id: "diesel_parts",
    name: "Precision Engine Parts",
    category: "commodity",
    weightKg: 2.8,
    basePrice: 105,
    description:
      "Forged pistons, injectors, and magnetos from New Chicago rail foundries. Vital for Blackwater oil derricks and mining pumps.",
  },

  // --- MELEE WEAPONS ---
  rusty_machete: {
    id: "rusty_machete",
    name: "Rusty Cleaver Machete",
    category: "weapon",
    weightKg: 1.5,
    basePrice: 60,
    description:
      "Heavy leaf-spring blade. Reliable in close quarters when every bullet is too expensive to waste.",
    weaponStats: {
      weaponId: "rusty_machete",
      minDamage: 12,
      maxDamage: 19,
      optimalRangeTiles: 1,
      maxRangeTiles: 1,
      snapShotAp: 3,
      aimedShotAp: null,
      baseAccuracy: 86,
      ammoType: null,
      magazineSize: 0,
      reloadAp: 0,
    },
  },
  cavalry_saber: {
    id: "cavalry_saber",
    name: "US Cavalry Officer Saber",
    category: "weapon",
    weightKg: 1.8,
    basePrice: 165,
    description:
      "Tempered high-carbon steel saber from old frontier forts. Swift, balanced, and lethal in close-quarters dueling.",
    weaponStats: {
      weaponId: "cavalry_saber",
      minDamage: 18,
      maxDamage: 27,
      optimalRangeTiles: 1,
      maxRangeTiles: 1,
      snapShotAp: 3,
      aimedShotAp: null,
      baseAccuracy: 90,
      ammoType: null,
      magazineSize: 0,
      reloadAp: 0,
    },
  },
  sledgehammer: {
    id: "sledgehammer",
    name: "Leadville Mining Sledge",
    category: "weapon",
    weightKg: 4.5,
    basePrice: 210,
    description:
      "Two-handed forged iron maul used to crack boulders and armored raiders alike. Slow swing, bone-crushing impact.",
    weaponStats: {
      weaponId: "sledgehammer",
      minDamage: 26,
      maxDamage: 40,
      optimalRangeTiles: 1,
      maxRangeTiles: 1,
      snapShotAp: 4,
      aimedShotAp: null,
      baseAccuracy: 82,
      ammoType: null,
      magazineSize: 0,
      reloadAp: 0,
    },
  },

  // --- PISTOLS & REVOLVERS ---
  derringer_22: {
    id: "derringer_22",
    name: "Gambler's .22 Derringer",
    category: "weapon",
    weightKg: 0.5,
    basePrice: 110,
    description:
      "Tiny two-shot vest pocket pistol favored by saloon cardsharps. Ultra-low 2 AP cost for rapid close-range shots.",
    weaponStats: {
      weaponId: "derringer_22",
      minDamage: 9,
      maxDamage: 15,
      optimalRangeTiles: 3,
      maxRangeTiles: 5,
      snapShotAp: 2,
      aimedShotAp: 4,
      baseAccuracy: 68,
      ammoType: "ammo_22",
      magazineSize: 2,
      reloadAp: 2,
    },
  },
  revolver_38: {
    id: "revolver_38",
    name: "Frontier .38 Revolver",
    category: "weapon",
    weightKg: 1.2,
    basePrice: 240,
    description:
      "Six-shooter sidearm with low Action Point cost. Fast on the draw at short-to-medium range.",
    weaponStats: {
      weaponId: "revolver_38",
      minDamage: 15,
      maxDamage: 23,
      optimalRangeTiles: 5,
      maxRangeTiles: 8,
      snapShotAp: 3,
      aimedShotAp: 5,
      baseAccuracy: 72,
      ammoType: "ammo_38",
      magazineSize: 6,
      reloadAp: 2,
    },
  },
  peacemaker_45: {
    id: "peacemaker_45",
    name: "Colt .45 Peacemaker",
    category: "weapon",
    weightKg: 1.4,
    basePrice: 460,
    description:
      "Heavy-frame single-action .45 Colt revolver. The iconic sidearm of Tombstone marshals and veteran trail bosses.",
    weaponStats: {
      weaponId: "peacemaker_45",
      minDamage: 22,
      maxDamage: 34,
      optimalRangeTiles: 6,
      maxRangeTiles: 9,
      snapShotAp: 3,
      aimedShotAp: 5,
      baseAccuracy: 76,
      ammoType: "ammo_45",
      magazineSize: 6,
      reloadAp: 2,
    },
  },

  // --- SHOTGUNS ---
  coach_shotgun_12g: {
    id: "coach_shotgun_12g",
    name: "Double-Barrel Coach Gun",
    category: "weapon",
    weightKg: 3.4,
    basePrice: 490,
    description:
      "Sawed-off 12-gauge scattergun. Devastating stopping power against raiders charging your wagon.",
    weaponStats: {
      weaponId: "coach_shotgun_12g",
      minDamage: 30,
      maxDamage: 46,
      optimalRangeTiles: 3,
      maxRangeTiles: 5,
      snapShotAp: 4,
      aimedShotAp: 5,
      baseAccuracy: 80,
      ammoType: "ammo_12g",
      magazineSize: 2,
      reloadAp: 2,
    },
  },
  pump_shotgun_12g: {
    id: "pump_shotgun_12g",
    name: "Trench 12G Pump Shotgun",
    category: "weapon",
    weightKg: 3.9,
    basePrice: 740,
    description:
      "Tubular-magazine repeating 12-gauge riot shotgun from New Chicago armories. Holds 6 shells of close-range devastation.",
    weaponStats: {
      weaponId: "pump_shotgun_12g",
      minDamage: 32,
      maxDamage: 48,
      optimalRangeTiles: 4,
      maxRangeTiles: 6,
      snapShotAp: 4,
      aimedShotAp: 5,
      baseAccuracy: 82,
      ammoType: "ammo_12g",
      magazineSize: 6,
      reloadAp: 3,
    },
  },

  // --- RIFLES & SMGS ---
  varmint_rifle_22: {
    id: "varmint_rifle_22",
    name: "Prairie .22 Varmint Rifle",
    category: "weapon",
    weightKg: 2.6,
    basePrice: 195,
    description:
      "Light bolt-action small-game rifle with crisp iron sights. Cheap to shoot and accurate for novice marksmen.",
    weaponStats: {
      weaponId: "varmint_rifle_22",
      minDamage: 13,
      maxDamage: 20,
      optimalRangeTiles: 8,
      maxRangeTiles: 12,
      snapShotAp: 3,
      aimedShotAp: 5,
      baseAccuracy: 76,
      ammoType: "ammo_22",
      magazineSize: 8,
      reloadAp: 2,
    },
  },
  lever_repeater_38: {
    id: "lever_repeater_38",
    name: "Winchester .38 Lever Repeater",
    category: "weapon",
    weightKg: 3.3,
    basePrice: 360,
    description:
      "Classic saddle-ring lever-action rifle sharing .38 Special ammo with frontier revolvers. High tube capacity and fast cycling.",
    weaponStats: {
      weaponId: "lever_repeater_38",
      minDamage: 19,
      maxDamage: 28,
      optimalRangeTiles: 9,
      maxRangeTiles: 14,
      snapShotAp: 3,
      aimedShotAp: 5,
      baseAccuracy: 77,
      ammoType: "ammo_38",
      magazineSize: 10,
      reloadAp: 2,
    },
  },
  bolt_rifle_308: {
    id: "bolt_rifle_308",
    name: "Grandfather's .308 Rifle",
    category: "weapon",
    weightKg: 3.8,
    basePrice: 420,
    description:
      "Your grandfather's scarred bolt-action hunting rifle. Deadly accuracy across the tactical map.",
    weaponStats: {
      weaponId: "bolt_rifle_308",
      minDamage: 24,
      maxDamage: 36,
      optimalRangeTiles: 14,
      maxRangeTiles: 19,
      snapShotAp: 4,
      aimedShotAp: 6,
      baseAccuracy: 78,
      ammoType: "ammo_308",
      magazineSize: 5,
      reloadAp: 2,
    },
  },
  grease_smg_9mm: {
    id: "grease_smg_9mm",
    name: "M3 'Grease Gun' 9mm SMG",
    category: "weapon",
    weightKg: 3.6,
    basePrice: 680,
    description:
      "Stamped-steel submachine gun favored by New Chicago rail syndicates. High magazine capacity and low AP cost.",
    weaponStats: {
      weaponId: "grease_smg_9mm",
      minDamage: 20,
      maxDamage: 31,
      optimalRangeTiles: 5,
      maxRangeTiles: 9,
      snapShotAp: 3,
      aimedShotAp: 4,
      baseAccuracy: 74,
      ammoType: "ammo_9mm",
      magazineSize: 15,
      reloadAp: 2,
    },
  },
  carbine_556: {
    id: "carbine_556",
    name: "New Denver 5.56 Carbine",
    category: "weapon",
    weightKg: 3.2,
    basePrice: 920,
    description:
      "Semi-automatic marksman carbine manufactured for the wealthy guard regiments of New Denver.",
    weaponStats: {
      weaponId: "carbine_556",
      minDamage: 22,
      maxDamage: 32,
      optimalRangeTiles: 11,
      maxRangeTiles: 16,
      snapShotAp: 3,
      aimedShotAp: 5,
      baseAccuracy: 82,
      ammoType: "ammo_556",
      magazineSize: 12,
      reloadAp: 2,
    },
  },
  sniper_rifle_762: {
    id: "sniper_rifle_762",
    name: "M24 7.62mm Sniper Rifle",
    category: "weapon",
    weightKg: 4.6,
    basePrice: 1350,
    description:
      "Long-barrel scoped precision rifle from pre-collapse military vaults. Unmatched range and lethal headshot capability.",
    weaponStats: {
      weaponId: "sniper_rifle_762",
      minDamage: 36,
      maxDamage: 54,
      optimalRangeTiles: 18,
      maxRangeTiles: 25,
      snapShotAp: 4,
      aimedShotAp: 6,
      baseAccuracy: 88,
      ammoType: "ammo_762",
      magazineSize: 5,
      reloadAp: 3,
    },
  },

  // --- AMMUNITION (8 CALIBERS) ---
  ammo_22: {
    id: "ammo_22",
    name: ".22 Rimfire Cartridge",
    category: "ammo",
    weightKg: 0.01,
    basePrice: 6,
    description: "Light rimfire round for pocket derringers and prairie varmint rifles.",
  },
  ammo_38: {
    id: "ammo_38",
    name: ".38 Special Round",
    category: "ammo",
    weightKg: 0.03,
    basePrice: 11,
    description: "Standard frontier cartridge for .38 revolvers and lever-action repeaters.",
  },
  ammo_9mm: {
    id: "ammo_9mm",
    name: "9mm Parabellum Round",
    category: "ammo",
    weightKg: 0.03,
    basePrice: 14,
    description: "Centerfire cartridge used in M3 Grease Gun submachine guns.",
  },
  ammo_45: {
    id: "ammo_45",
    name: ".45 Colt Heavy Round",
    category: "ammo",
    weightKg: 0.04,
    basePrice: 15,
    description: "Heavy-grain lead slug for Colt .45 Peacemaker revolvers.",
  },
  ammo_12g: {
    id: "ammo_12g",
    name: "12-Gauge Buckshot Shell",
    category: "ammo",
    weightKg: 0.06,
    basePrice: 16,
    description: "Heavy lead buckshot shell for coach guns and pump-action trench shotguns.",
  },
  ammo_308: {
    id: "ammo_308",
    name: ".308 Rifle Cartridge",
    category: "ammo",
    weightKg: 0.05,
    basePrice: 18,
    description: "High-powered brass rifle round. Make every shot count.",
  },
  ammo_556: {
    id: "ammo_556",
    name: "5.56mm Military Round",
    category: "ammo",
    weightKg: 0.04,
    basePrice: 24,
    description: "High-velocity military carbine ammunition.",
  },
  ammo_762: {
    id: "ammo_762",
    name: "7.62mm Match Grade Round",
    category: "ammo",
    weightKg: 0.06,
    basePrice: 32,
    description: "Precision long-range brass cartridge for 7.62mm sniper rifles.",
  },
};

export const TRANSPORTS: Record<TransportId, TransportDefinition> = {
  on_foot: {
    id: "on_foot",
    name: "On Foot (Backpack Only)",
    propulsion: "human",
    maxCargoKg: 35,
    baseSpeedKmh: 4.0,
    price: 0,
    waterPerDay: 0,
    foragePerDay: 0,
    fuelLitersPer10Km: 0,
    availableInTiers: ["frontier_town", "major_city"],
    description:
      "Walking the wasteland with only what your back can carry. Zero animal or fuel upkeep, but severely limited cargo.",
    terrainSpeedMultipliers: {
      old_highway: 1.0,
      scorched_flats: 0.95,
      sand_dunes: 0.8,
      rocky_canyon: 0.9,
    },
  },
  hand_cart: {
    id: "hand_cart",
    name: "Wooden Handcart",
    propulsion: "human",
    maxCargoKg: 65,
    baseSpeedKmh: 3.7,
    price: 120,
    waterPerDay: 0,
    foragePerDay: 0,
    fuelLitersPer10Km: 0,
    availableInTiers: ["frontier_town", "major_city"],
    description:
      "A two-wheel wooden pushcart pulled by hand.Nearly doubles personal capacity with zero animal feed or fuel costs.",
    terrainSpeedMultipliers: {
      old_highway: 1.05,
      scorched_flats: 0.9,
      sand_dunes: 0.65,
      rocky_canyon: 0.8,
    },
  },
  old_donkey: {
    id: "old_donkey",
    name: "Grandfather's Pack Donkey",
    propulsion: "animal",
    maxCargoKg: 90,
    baseSpeedKmh: 5.8,
    price: 260,
    waterPerDay: 2,
    foragePerDay: 2,
    fuelLitersPer10Km: 0,
    availableInTiers: ["frontier_town"],
    description:
      "Stubborn, sure-footed, and frugal. Carries 90 kg of saddlebags across rocky canyons and dunes without complaint.",
    terrainSpeedMultipliers: {
      old_highway: 1.05,
      scorched_flats: 1.0,
      sand_dunes: 0.92,
      rocky_canyon: 1.0,
    },
  },
  pack_mule_team: {
    id: "pack_mule_team",
    name: "Twin Pack Mules",
    propulsion: "animal",
    maxCargoKg: 165,
    baseSpeedKmh: 6.4,
    price: 490,
    waterPerDay: 3.5,
    foragePerDay: 3.5,
    fuelLitersPer10Km: 0,
    availableInTiers: ["frontier_town"],
    description:
      "A matched pair of hardy mountain mules with leather pack frames. Excels in rocky canyons where wheeled carts struggle.",
    terrainSpeedMultipliers: {
      old_highway: 1.08,
      scorched_flats: 1.02,
      sand_dunes: 0.9,
      rocky_canyon: 1.05,
    },
  },
  wooden_cart_donkey: {
    id: "wooden_cart_donkey",
    name: "Two-Wheel Cart + Donkey",
    propulsion: "animal",
    maxCargoKg: 240,
    baseSpeedKmh: 4.8,
    price: 680,
    waterPerDay: 3,
    foragePerDay: 3,
    fuelLitersPer10Km: 0,
    availableInTiers: ["frontier_town"],
    description:
      "A creaking timber cart hitched to your donkey. Hauls 240 kg of bulk grain, ore, and hides, though slower in deep sand.",
    terrainSpeedMultipliers: {
      old_highway: 1.15,
      scorched_flats: 0.95,
      sand_dunes: 0.65,
      rocky_canyon: 0.8,
    },
  },
  heavy_wagon_horse: {
    id: "heavy_wagon_horse",
    name: "Prairie Wagon + Draft Horse",
    propulsion: "animal",
    maxCargoKg: 480,
    baseSpeedKmh: 8.5,
    price: 1650,
    waterPerDay: 6,
    foragePerDay: 5,
    fuelLitersPer10Km: 0,
    availableInTiers: ["frontier_town", "major_city"],
    description:
      "A reinforced merchant wagon pulled by a muscular Deadwood draft horse. Fast on roads and offers solid cover in combat.",
    terrainSpeedMultipliers: {
      old_highway: 1.25,
      scorched_flats: 1.0,
      sand_dunes: 0.7,
      rocky_canyon: 0.85,
    },
  },
  brahmin_freight_wagon: {
    id: "brahmin_freight_wagon",
    name: "Twin-Headed Ox Freight Wagon",
    propulsion: "animal",
    maxCargoKg: 780,
    baseSpeedKmh: 6.5,
    price: 2650,
    waterPerDay: 9,
    foragePerDay: 8,
    fuelLitersPer10Km: 0,
    availableInTiers: ["frontier_town", "major_city"],
    description:
      "Heavy iron-rimmed Conestoga freighter pulled by mutant two-headed oxen from Tombstone Crossing. Hauls 780 kg without needing Gasoline.",
    terrainSpeedMultipliers: {
      old_highway: 1.18,
      scorched_flats: 1.0,
      sand_dunes: 0.78,
      rocky_canyon: 0.82,
    },
  },
  scrap_motorcycle: {
    id: "scrap_motorcycle",
    name: "Wasteland Scrambler Bike",
    propulsion: "motor",
    maxCargoKg: 140,
    baseSpeedKmh: 26.0,
    price: 3100,
    waterPerDay: 0,
    foragePerDay: 0,
    fuelLitersPer10Km: 0.8,
    availableInTiers: ["major_city"],
    description:
      "Built in Saint Louis machine shops. Outruns almost any raider pack, consumes zero food when parked, and carries 140 kg.",
    terrainSpeedMultipliers: {
      old_highway: 1.35,
      scorched_flats: 1.1,
      sand_dunes: 0.75,
      rocky_canyon: 0.9,
    },
  },
  desert_dune_buggy: {
    id: "desert_dune_buggy",
    name: "V6 Interceptor Buggy",
    propulsion: "motor",
    maxCargoKg: 380,
    baseSpeedKmh: 32.0,
    price: 4650,
    waterPerDay: 0,
    foragePerDay: 0,
    fuelLitersPer10Km: 1.3,
    availableInTiers: ["major_city"],
    description:
      "Long-travel suspension roll-cage buggy with paddle tires. Flies across sand dunes and scorched flats with 380 kg of cargo.",
    terrainSpeedMultipliers: {
      old_highway: 1.3,
      scorched_flats: 1.25,
      sand_dunes: 1.1,
      rocky_canyon: 0.95,
    },
  },
  armored_pickup: {
    id: "armored_pickup",
    name: "New Denver V8 Cargo Truck",
    propulsion: "motor",
    maxCargoKg: 1200,
    baseSpeedKmh: 36.0,
    price: 6400,
    waterPerDay: 0,
    foragePerDay: 0,
    fuelLitersPer10Km: 2.0,
    availableInTiers: ["major_city"],
    description:
      "The pinnacle of merchant power. Hauls 1,200 kg at highway speeds, available only in metropolitan industrial hubs.",
    terrainSpeedMultipliers: {
      old_highway: 1.4,
      scorched_flats: 1.15,
      sand_dunes: 0.7,
      rocky_canyon: 0.8,
    },
  },
};

export const SETTLEMENTS: Record<SettlementId, SettlementDefinition> = {
  dust_creek: {
    id: "dust_creek",
    name: "Dust Creek",
    tier: "frontier_town",
    subtitle: "Humble Frontier Farming & Well Settlement",
    lore: "A sun-baked cluster of wooden shacks built around a deep artesian well where your grandfather spent his final years. Water, corn, and donkey forage are cheap here, but manufactured tools and leather fetch high prices.",
    coordinates: { x: 140, y: 480 },
    produces: ["water", "food_rations", "animal_forage"],
    demands: ["raw_leather", "tools", "antibiotics"],
    priceMultipliers: {
      water: 0.55,
      food_rations: 0.65,
      animal_forage: 0.5,
      raw_leather: 1.45,
      tools: 1.55,
      antibiotics: 1.5,
      salt: 0.9,
    },
    baseStock: {
      water: 85,
      food_rations: 65,
      animal_forage: 95,
      salt: 18,
      raw_leather: 4,
      field_bandage: 10,
      rusty_machete: 3,
      derringer_22: 2,
      varmint_rifle_22: 2,
      ammo_22: 35,
      ammo_38: 18,
      ammo_308: 12,
    },
    strictContrabandCheck: false,
    npcs: {
      general_trader: {
        role: "general_trader",
        name: "Silas Miller",
        title: "Dust Creek General Storekeeper",
        greeting:
          "Your granddaddy was an honest man, kid. Kept that old .308 oiled till his last breath. If you're heading northeast to Deadwood Gulch or south to Tombstone Crossing, pack extra water.",
        loreDialogue:
          "We pump clean water and grow dry corn, and that's about all Dust Creek has to its name. Bring us cured leather from Deadwood or machinist tools from the eastern cities and I'll pay you handsomely.",
        tipDialogue:
          "Buy Water and Forage here while it's dirt cheap. Ranchers in Deadwood Gulch and Tombstone Crossing pay premium prices for clean water.",
      },
      transport_master: {
        role: "transport_master",
        name: "Old Barnaby",
        title: "Corral & Cart Wright",
        greeting:
          "That old donkey of your grandpa's still has sturdy legs! Once you've turned a few hundred dollars profit, come back for Twin Pack Mules or a Two-Wheel Cart.",
        loreDialogue:
          "Don't go dreaming of gasoline motors out here in the scrublands. Donkeys and mules eat dry grass and never blow a head gasket.",
        tipDialogue:
          "Upgrading from a Pack Donkey (90 kg) to Twin Pack Mules (165 kg) or a Two-Wheel Cart (240 kg) lets you haul heavy bulk cargo.",
      },
      sheriff: {
        role: "sheriff",
        name: "Marshal Wyatt Cole",
        title: "Frontier Peacekeeper",
        greeting:
          "Keep your rifle loaded on the trail, merchant. Scavengers have been sniffing around the creek road ever since the dry season started.",
        loreDialogue:
          "Out here on the frontier, we don't care if you haul canyon moonshine. Just don't try sneaking it past the blue-coat inspectors in Saint Louis, New Denver, or New Chicago.",
        tipDialogue:
          "Use Headshots on unarmored raiders for 1.75x damage, or Legshots on fast melee chargers to cut their movement AP in half!",
      },
      saloon_barkeep: {
        role: "saloon_barkeep",
        name: "Maeve Holliday",
        title: "The Rusty Spur Saloon",
        greeting:
          "Pour yourself a glass of well-water or corn whiskey, stranger. Teamsters pass through every evening talking about which town is starving and which is booming.",
        loreDialogue:
          "Information makes more millionaires than bullets. Pay for a round and I'll tell you where prices just spiked.",
        tipDialogue:
          "Hiring a mercenary guard costs a daily wage and extra rations, but having a second gun on the tactical grid can save your life and your cargo.",
      },
    },
  },

  deadwood_gulch: {
    id: "deadwood_gulch",
    name: "Deadwood Gulch",
    tier: "frontier_town",
    subtitle: "Old West Cattle Ranching & Tannery Outpost",
    lore: "A rugged stockyard town smelling of woodsmoke, curing hides, and horse manure. Wranglers here raise the finest draft horses, distill oak-aged whiskey, and tan heavy leather, but they are chronically short on clean water and ammunition.",
    coordinates: { x: 330, y: 230 },
    produces: ["raw_leather", "smoked_jerky", "whiskey_barrel"],
    demands: ["water", "salt", "ammo_308", "ammo_38", "tools"],
    priceMultipliers: {
      raw_leather: 0.58,
      smoked_jerky: 0.62,
      whiskey_barrel: 0.68,
      water: 1.65,
      salt: 1.55,
      ammo_308: 1.5,
      ammo_38: 1.45,
      tools: 1.4,
      animal_forage: 0.8,
    },
    baseStock: {
      raw_leather: 45,
      smoked_jerky: 50,
      whiskey_barrel: 22,
      animal_forage: 40,
      water: 14,
      food_rations: 25,
      field_bandage: 10,
      cavalry_saber: 2,
      revolver_38: 3,
      lever_repeater_38: 2,
      coach_shotgun_12g: 2,
      ammo_38: 18,
      ammo_12g: 16,
    },
    strictContrabandCheck: false,
    npcs: {
      general_trader: {
        role: "general_trader",
        name: "Boone Callahan",
        title: "Gulch Hide & Provision Factor",
        greeting:
          "If you brought clean water or desert salt, unload it right now! My tanners are parched and we've got stacks of Cured Leather and Oak Whiskey Casks ready to ship.",
        loreDialogue:
          "The aristocrats in Saint Louis love our leather for their boots and upholstery, and the miners in Leadville Shaft can't work without our Smoked Jerky and Whiskey.",
        tipDialogue:
          "Load up on Raw Leather, Smoked Jerky, and Whiskey Barrels here. Sell the Jerky at Leadville Shaft, and take the Leather east to Saint Louis.",
      },
      transport_master: {
        role: "transport_master",
        name: "Calamity Jane Finch",
        title: "Deadwood Horse Wrangler",
        greeting:
          "A donkey's fine for a peddler, friend, but a true caravan master rides behind a Deadwood Draft Horse pulling a Prairie Wagon!",
        loreDialogue:
          "Our horses drink more water than a mule, sure, but they haul 480 kilos at a brisk trot down the Old Highway.",
        tipDialogue:
          "Save $1,650 for the Prairie Wagon + Draft Horse, or $2,650 for the massive Twin-Headed Ox Freight Wagon.",
      },
      sheriff: {
        role: "sheriff",
        name: "Sheriff Virgil Earp",
        title: "Gulch Lawman",
        greeting:
          "Cattle rustlers and highwaymen think they own the canyon pass to Leadville. Put a few of 'em in the dirt and the Ranchers' Association will make it worth your while.",
        loreDialogue:
          "Keep an eye on your ammo reserves. Out here, a man with an empty rifle is just a walking loot crate.",
        tipDialogue:
          "In combat, crouch behind rocks or your own wagon to boost defense against enemy gunfire.",
      },
      saloon_barkeep: {
        role: "saloon_barkeep",
        name: "Doc Hollister",
        title: "The Longhorn Saloon",
        greeting:
          "Step up to the mahogany, merchant. Looking for market rumors or a hired gun who knows how to handle a coach shotgun?",
        loreDialogue:
          "Lots of drifters pass between the mines of Leadville and the river docks of Saint Louis.",
        tipDialogue:
          "The Winchester .38 Lever Repeater shares .38 Special ammo with your Frontier Revolver — great for simplifying your ammo logistics.",
      },
    },
  },

  leadville_shaft: {
    id: "leadville_shaft",
    name: "Leadville Shaft",
    tier: "frontier_town",
    subtitle: "Canyon Lead Mine & Munitions Foundry",
    lore: "Carved into a jagged red-rock canyon, Leadville's blasts echo day and night. Miners smelt scrap steel and copper ore while hand-pressing cartridges, working up a fierce thirst for jerky, canned beef, and whiskey.",
    coordinates: { x: 520, y: 540 },
    produces: [
      "scrap_metal",
      "copper_ore",
      "ammo_22",
      "ammo_38",
      "ammo_45",
      "ammo_308",
      "ammo_12g",
      "moonshine",
    ],
    demands: ["smoked_jerky", "canned_beef", "food_rations", "water", "antibiotics", "whiskey_barrel"],
    priceMultipliers: {
      scrap_metal: 0.55,
      copper_ore: 0.56,
      ammo_22: 0.65,
      ammo_38: 0.65,
      ammo_45: 0.68,
      ammo_308: 0.68,
      ammo_12g: 0.7,
      moonshine: 0.6,
      smoked_jerky: 1.55,
      canned_beef: 1.55,
      food_rations: 1.5,
      water: 1.6,
      antibiotics: 1.65,
      whiskey_barrel: 1.45,
    },
    baseStock: {
      scrap_metal: 65,
      copper_ore: 55,
      ammo_22: 90,
      ammo_38: 85,
      ammo_45: 60,
      ammo_308: 70,
      ammo_12g: 60,
      moonshine: 32,
      sledgehammer: 4,
      revolver_38: 4,
      lever_repeater_38: 3,
      bolt_rifle_308: 3,
      coach_shotgun_12g: 3,
      water: 12,
      food_rations: 10,
      field_bandage: 12,
    },
    strictContrabandCheck: false,
    npcs: {
      general_trader: {
        role: "general_trader",
        name: "Gideon 'Slag' Vance",
        title: "Foundry Quartermaster & Gunsmith",
        greeting:
          "You smell like fresh air and trail dust! Did you bring Smoked Jerky, Canned Beef, or Antibiotics for the pit crews? We've got Salvaged Steel, Copper Ore, and fresh-pressed brass ammo ready to deal.",
        loreDialogue:
          "Every bullet fired between Dust Creek and New Chicago starts as lead and copper pulled from our shaft. We also distill Canyon Moonshine in the back tunnels.",
        tipDialogue:
          "Haul Smelted Copper Ore and Salvaged Steel from here to New Chicago or Saint Louis for massive industrial profits.",
      },
      transport_master: {
        role: "transport_master",
        name: "Hector Ironwheel",
        title: "Mine Muleteer",
        greeting:
          "The canyon road is murder on wooden spokes, merchant. Watch your cargo weight when climbing out of the shaft with heavy steel and copper ingots!",
        loreDialogue:
          "Twin Pack Mules handle rocky canyons better than any two-wheel cart.",
        tipDialogue:
          "If raiders catch you while hauling heavy ore, remember you can Jettison a few ingots to regain top speed and flee.",
      },
      sheriff: {
        role: "sheriff",
        name: "Captain Rooster Cogburn",
        title: "Union Mine Security Chief",
        greeting:
          "Dynamite thieves and canyon ambushes are my daily headache. Help me clear the rocky pass and the Miners' Guild pays cold hard script.",
        loreDialogue:
          "Use Aimed Shots or Headshots when fighting armored raiders in the canyon. Costs more AP, but the extra accuracy and crit multiplier save precious brass.",
        tipDialogue:
          "High Perception boosts your accuracy on every single ranged shot.",
      },
      saloon_barkeep: {
        role: "saloon_barkeep",
        name: "Ruby Red",
        title: "The Canary & Pickaxe Dive",
        greeting:
          "Miners drink hard when they survive a shift. Want to buy a rumor on where the next supply shortage hit, or hire an ex-pit guard?",
        loreDialogue:
          "The rich folks in New Denver and New Chicago pretend they don't drink our Canyon Moonshine, yet they pay double for every jug that slips past their gates.",
        tipDialogue:
          "Charisma not only improves trade prices at every shop, it helps you bluff city gate inspectors when carrying Contraband.",
      },
    },
  },

  blackwater_rig: {
    id: "blackwater_rig",
    name: "Blackwater Rig",
    tier: "frontier_town",
    subtitle: "Scorched Desert Oil Derrick & Refinery",
    lore: "Rising from the salt flats like an iron skeleton, Blackwater Rig pumps and distills the last accessible crude oil in the region. Gasoline is cheap here, but the rigs desperately need New Chicago Engine Parts and clean Water.",
    coordinates: { x: 620, y: 220 },
    produces: ["gasoline", "salt"],
    demands: ["water", "food_rations", "diesel_parts", "raw_leather", "tools"],
    priceMultipliers: {
      gasoline: 0.52,
      salt: 0.55,
      water: 1.85,
      food_rations: 1.65,
      animal_forage: 1.75,
      diesel_parts: 1.65,
      raw_leather: 1.4,
      tools: 1.45,
    },
    baseStock: {
      gasoline: 120,
      salt: 75,
      tools: 8,
      water: 10,
      food_rations: 12,
      animal_forage: 8,
      field_bandage: 10,
      derringer_22: 3,
      revolver_38: 2,
      ammo_38: 25,
      ammo_12g: 20,
    },
    strictContrabandCheck: false,
    npcs: {
      general_trader: {
        role: "general_trader",
        name: "Oilman Jedediah Clamp",
        title: "Refinery Commissary Boss",
        greeting:
          "Welcome to the hottest furnace on earth, traveler! Bring us Water, Rations, and Precision Engine Parts so my roughnecks and drill heads don't seize up, and I'll fill your tanks with Refined Gasoline at half price.",
        loreDialogue:
          "The metropolises of Saint Louis, New Denver, and New Chicago can't run their motorcycles, buggies, and V8 trucks without Blackwater fuel.",
        tipDialogue:
          "Bring Precision Engine Parts from New Chicago to Blackwater Rig, then haul cheap Gasoline back to the cities for a lucrative two-way loop!",
      },
      transport_master: {
        role: "transport_master",
        name: "Grease-Monkey Sparks",
        title: "Rig Pump & Motor Tech",
        greeting:
          "Once you buy a Scrambler Bike, V6 Buggy, or V8 Truck in the major cities, Blackwater Rig is your best friend for cheap fuel.",
        loreDialogue:
          "The V6 Interceptor Buggy is a marvel on these alkali dunes — its paddle tires barely slow down in deep sand.",
        tipDialogue:
          "Even before you own a motor vehicle, hauling barrels of Gasoline from Blackwater Rig to New Denver or New Chicago is a goldmine.",
      },
      sheriff: {
        role: "sheriff",
        name: "Warden Cassius Holt",
        title: "Derrick Security Marshal",
        greeting:
          "Fuel raiders ride out of the salt flats trying to hijack tankers. Clear 'em out and the Rig Syndicate pays top bounties.",
        loreDialogue:
          "Out in the open flats, long-range rifles rule the battlefield. Keep your distance from shotgun and sledgehammer raiders.",
        tipDialogue:
          "Check the danger rating on desert routes before departing.",
      },
      saloon_barkeep: {
        role: "saloon_barkeep",
        name: "Salty Pete",
        title: "The Flaming Barrel Canteen",
        greeting:
          "Careful where you strike a match in here, kid. Everything's soaked in crude oil and cheap whiskey.",
        loreDialogue:
          "Tanker drivers always know which metropolis is paying the highest premium for fuel and medicine.",
        tipDialogue:
          "Buy a rumor whenever you have spare cash — catching a 2.4x price spike turns a good trip into a fortune.",
      },
    },
  },

  tombstone_crossing: {
    id: "tombstone_crossing",
    name: "Tombstone Crossing",
    tier: "frontier_town",
    subtitle: "Old West Frontier Livestock & Leather Hub",
    lore: "Built around an old stone railway bridge and sprawling brahmin corrals, Tombstone Crossing is the rowdiest cowtown in the southwest. Vaqueros and gunfighters pack Stockyard Canned Beef, Cured Leather, and Oak Whiskey, while paying top dollar for Salt, Water, and .45 Colt brass.",
    coordinates: { x: 300, y: 620 },
    produces: ["canned_beef", "raw_leather", "whiskey_barrel", "animal_forage"],
    demands: ["water", "salt", "tools", "antibiotics", "ammo_45"],
    priceMultipliers: {
      canned_beef: 0.58,
      raw_leather: 0.6,
      whiskey_barrel: 0.62,
      animal_forage: 0.6,
      water: 1.5,
      salt: 1.6,
      tools: 1.5,
      antibiotics: 1.55,
      ammo_45: 1.45,
    },
    baseStock: {
      canned_beef: 60,
      raw_leather: 50,
      whiskey_barrel: 35,
      animal_forage: 70,
      smoked_jerky: 30,
      water: 20,
      food_rations: 30,
      field_bandage: 12,
      cavalry_saber: 3,
      derringer_22: 3,
      peacemaker_45: 4,
      lever_repeater_38: 3,
      coach_shotgun_12g: 3,
      ammo_22: 40,
      ammo_38: 35,
      ammo_45: 30,
      ammo_12g: 25,
    },
    strictContrabandCheck: false,
    npcs: {
      general_trader: {
        role: "general_trader",
        name: "Don Esteban Morales",
        title: "Tombstone Stockyard & Cannery Baron",
        greeting:
          "Bienvenidos to Tombstone Crossing, caravaner! Bring my stockyards Desert Salt to cure our beef and Machinist Tools for our canning presses, and you can load your wagons with Canned Beef and Brahmin Leather at rock-bottom prices.",
        loreDialogue:
          "Our Stockyard Canned Beef feeds the rail crews in New Chicago and the miners in Leadville Shaft. Nothing beats sealed tin protein on a long haul.",
        tipDialogue:
          "Buy Canned Beef and Whiskey Barrels here, then follow the Southern Trunk Railway east to New Chicago for massive returns.",
      },
      transport_master: {
        role: "transport_master",
        name: "Buckskin Bob Pickett",
        title: "Brahmin Ox & Wagon Drover",
        greeting:
          "You want real frontier hauling power? Hitch your future to a Twin-Headed Ox Freight Wagon — 780 kilos of capacity and tough enough to shrug off desert heat!",
        loreDialogue:
          "We breed the biggest two-headed brahmin oxen in the southwest right here in Tombstone Crossing.",
        tipDialogue:
          "The Twin-Headed Ox Freight Wagon ($2,650) carries 780 kg without needing expensive Gasoline — ideal for heavy ore and canned beef runs.",
      },
      sheriff: {
        role: "sheriff",
        name: "Marshal Johnny Ringo",
        title: "Tombstone Ranger Captain",
        greeting:
          "Every fast-draw kid in the territory comes to Tombstone Crossing with a Colt .45 Peacemaker on his hip. Keep your iron holstered in town and save your lead for the border bandits.",
        loreDialogue:
          "The Colt .45 Peacemaker hits harder than a .38 revolver and only costs 3 AP for a snap shot.",
        tipDialogue:
          "Aim for the legs when a sledgehammer bruiser charges your firing line — crippling their legs drops their movement speed and AP!",
      },
      saloon_barkeep: {
        role: "saloon_barkeep",
        name: "Lola Montez",
        title: "The Oriental & Birdcage Saloon",
        greeting:
          "Faro tables are hot and the whiskey's cold, darling. Looking to hire a Tombstone gunslinger or hear which city is starving for beef?",
        loreDialogue:
          "Caravans heading east to New Chicago pass through here every week with news from the Great Lakes.",
        tipDialogue:
          "Django 'Six-Six' Morales drinks at the back table — he's a crack shot with a .45 Peacemaker if you can afford his hiring fee.",
      },
    },
  },

  saint_louis: {
    id: "saint_louis",
    name: "Saint Louis",
    tier: "major_city",
    subtitle: "Educated Riverfront Metropolis & Medical Hub",
    lore: "Behind brick fortifications and streetlamps, Saint Louis preserves pre-collapse universities, pharmaceutical labs, and cobblestone avenues. Wealthy merchants in tailored coats sip espresso, sell modern Antibiotics and Motorcycles, and pay dearly for frontier Raw Leather, Copper Ore, and Scrap Steel.",
    coordinates: { x: 800, y: 520 },
    produces: ["antibiotics", "luxury_cigars", "tools", "field_bandage"],
    demands: ["raw_leather", "scrap_metal", "copper_ore", "canned_beef", "moonshine"],
    priceMultipliers: {
      antibiotics: 0.62,
      luxury_cigars: 0.6,
      tools: 0.68,
      field_bandage: 0.7,
      raw_leather: 1.65,
      scrap_metal: 1.55,
      copper_ore: 1.5,
      canned_beef: 1.45,
      food_rations: 1.4,
      moonshine: 1.85,
      gasoline: 1.35,
    },
    baseStock: {
      antibiotics: 45,
      luxury_cigars: 50,
      tools: 40,
      field_bandage: 60,
      gasoline: 35,
      water: 50,
      food_rations: 30,
      animal_forage: 30,
      cavalry_saber: 4,
      revolver_38: 5,
      peacemaker_45: 4,
      bolt_rifle_308: 4,
      grease_smg_9mm: 3,
      carbine_556: 3,
      ammo_38: 50,
      ammo_9mm: 60,
      ammo_45: 45,
      ammo_308: 45,
      ammo_556: 40,
    },
    strictContrabandCheck: true,
    npcs: {
      general_trader: {
        role: "general_trader",
        name: "Julian Vanderbilt III",
        title: "Director of the Saint Louis Mercantile Exchange",
        greeting:
          "Ah, a frontier caravaner! Mind the mud on the parquet floor. If you have brought Cured Leather from Deadwood or Tombstone, or Copper and Steel from Leadville, our guild will compensate you generously.",
        loreDialogue:
          "Here in Saint Louis, we maintain civilized standards — university chemists synthesize true Antibiotics, and our artisans roll fine Reserve Cigars.",
        tipDialogue:
          "Sell Raw Leather and Copper Ore here, then buy Antibiotics and Luxury Cigars to sell in the frontier towns or northern cities!",
      },
      transport_master: {
        role: "transport_master",
        name: "Chief Engineer Alistair Sterling",
        title: "Saint Louis Motorworks & Carriage Guild",
        greeting:
          "Tired of crawling across the wasteland behind a donkey? Behold the Wasteland Scrambler Motorcycle, the V6 Interceptor Buggy, and the V8 Cargo Truck!",
        loreDialogue:
          "Internal combustion is the mark of an educated merchant. Just ensure you carry sufficient Refined Gasoline before venturing back into the frontier.",
        tipDialogue:
          "The Wasteland Scrambler Bike ($3,100) travels at 26 km/h — nearly 5x faster than a donkey — making high-value Antibiotic and Cigar runs lightning fast.",
      },
      sheriff: {
        role: "sheriff",
        name: "Commissioner Arthur Pendelton",
        title: "Metropolitan Constabulary HQ",
        greeting:
          "State your business, caravaner. Saint Louis strictly prohibits unlicensed Canyon Moonshine. Keep our highways clear of highwaymen, however, and the City Council authorizes substantial bounties.",
        loreDialogue:
          "Law and order separate Saint Louis from the lawless gulches of the west.",
        tipDialogue:
          "Entering Saint Louis, New Denver, or New Chicago with Moonshine triggers a Contraband Inspection. High Charisma lets you talk your way past the guards!",
      },
      saloon_barkeep: {
        role: "saloon_barkeep",
        name: "Madame Celeste",
        title: "The Gilded Steamboat Lounge",
        greeting:
          "Welcome to the Steamboat Lounge. Our patrons include commodity brokers, off-duty constables, and elite mercenaries looking for a wealthy caravan to escort.",
        loreDialogue:
          "When a drought or mine strike hits the western frontier, news reaches our telegraph office first.",
        tipDialogue:
          "Elite mercenaries in major cities have higher accuracy and better weapons than frontier drifters.",
      },
    },
  },

  new_denver: {
    id: "new_denver",
    name: "New Denver",
    tier: "major_city",
    subtitle: "Walled Industrial Capital & High-Plateau Citadel",
    lore: "Towering steel walls protect New Denver's smokestacks, armories, and electric grid. Ruled by wealthy industrial barons and military engineers, it is the premier hub for V8 Cargo Trucks, 5.56 Carbines, and 7.62mm Sniper Rifles, with an insatiable appetite for Gasoline, Smoked Jerky, and smuggled Moonshine.",
    coordinates: { x: 860, y: 160 },
    produces: ["carbine_556", "sniper_rifle_762", "ammo_556", "ammo_762", "tools", "antibiotics"],
    demands: ["gasoline", "smoked_jerky", "scrap_metal", "copper_ore", "luxury_cigars", "moonshine"],
    priceMultipliers: {
      tools: 0.6,
      carbine_556: 0.78,
      sniper_rifle_762: 0.8,
      ammo_556: 0.7,
      ammo_762: 0.72,
      antibiotics: 0.75,
      gasoline: 1.55,
      smoked_jerky: 1.6,
      scrap_metal: 1.5,
      copper_ore: 1.52,
      luxury_cigars: 1.55,
      moonshine: 2.1,
    },
    baseStock: {
      tools: 55,
      antibiotics: 35,
      field_bandage: 50,
      carbine_556: 6,
      sniper_rifle_762: 3,
      pump_shotgun_12g: 4,
      coach_shotgun_12g: 4,
      bolt_rifle_308: 5,
      ammo_556: 90,
      ammo_762: 55,
      ammo_308: 60,
      ammo_12g: 50,
      gasoline: 40,
      water: 45,
      food_rations: 40,
    },
    strictContrabandCheck: true,
    npcs: {
      general_trader: {
        role: "general_trader",
        name: "Baroness Victoria Kensington",
        title: "New Denver Armory & Industrial Syndicate",
        greeting:
          "Time is money in New Denver, trader. Our factories require Blackwater Gasoline, Leadville Steel & Copper, and Deadwood Jerky for our workforce. In exchange, we offer military-grade 5.56 Carbines and 7.62mm Sniper Rifles.",
        loreDialogue:
          "The frontier relies on beasts of burden, while New Denver rebuilds the modern world. Profit belongs to those who bridge the gap between the two.",
        tipDialogue:
          "Hauling Gasoline from Blackwater Rig or Luxury Cigars from Saint Louis to New Denver yields massive profits.",
      },
      transport_master: {
        role: "transport_master",
        name: "Foreman Marcus Vance",
        title: "Citadel Heavy Automotive Foundry",
        greeting:
          "Looking at the V8 Cargo Truck? Reinforced steel bed, 1,200 kg capacity, 36 km/h cruising speed. Once you drive one of these, you own the trade routes.",
        loreDialogue:
          "A V8 Truck burns 2 Liters of Gasoline per 10 km, so always keep at least 15-20 Liters in your tank before leaving the city.",
        tipDialogue:
          "If you want high speed over desert sand dunes with lighter fuel burn, check out the V6 Interceptor Buggy (380 kg).",
      },
      sheriff: {
        role: "sheriff",
        name: "Provost Marshal Sterling Graves",
        title: "Citadel High Command",
        greeting:
          "New Denver enforces strict customs inspections at the Northern Gate. Keep your manifest clean of contraband, or take a High Command Bounty to prove your loyalty.",
        loreDialogue:
          "Warlord gangs along the northern highway carry automatic weapons and long rifles. Do not engage them without cover and extra bandages.",
        tipDialogue:
          "The M24 7.62mm Sniper Rifle has an optimal range of 11 tiles — pair it with Headshots to eliminate enemy bosses before they can close in.",
      },
      saloon_barkeep: {
        role: "saloon_barkeep",
        name: "Victor 'The Velvet' Moretti",
        title: "The Mile-High Officers' Club",
        greeting:
          "Bourbon on ice, merchant? Only the wealthiest caravan bosses make it up to the Mile-High Club. Incidentally, my back-room buyers pay 210% for Canyon Moonshine if you slipped any past the gate...",
        loreDialogue:
          "All the big trade syndicates broker their deals right at these tables.",
        tipDialogue:
          "Combine a V8 Truck with hired mercenaries and no raider gang in the wasteland can stop your caravan.",
      },
    },
  },

  new_chicago: {
    id: "new_chicago",
    name: "New Chicago",
    tier: "major_city",
    subtitle: "Major US Industrial & Rail Metropolis",
    lore: "Anchored around steel blast furnaces, armored rail yards, and Lake Michigan wind turbines, New Chicago is an industrial powerhouse. Union machinists manufacture Precision Engine Parts, Pump Shotguns, and 9mm Grease Guns, while importing tons of Canned Beef, Copper Ore, Gasoline, and Oak Whiskey.",
    coordinates: { x: 880, y: 650 },
    produces: [
      "diesel_parts",
      "tools",
      "pump_shotgun_12g",
      "grease_smg_9mm",
      "ammo_9mm",
      "ammo_12g",
    ],
    demands: [
      "canned_beef",
      "copper_ore",
      "scrap_metal",
      "gasoline",
      "whiskey_barrel",
      "moonshine",
    ],
    priceMultipliers: {
      diesel_parts: 0.56,
      tools: 0.62,
      pump_shotgun_12g: 0.75,
      grease_smg_9mm: 0.75,
      ammo_9mm: 0.65,
      ammo_12g: 0.72,
      canned_beef: 1.65,
      copper_ore: 1.6,
      scrap_metal: 1.5,
      gasoline: 1.5,
      whiskey_barrel: 1.55,
      moonshine: 2.0,
    },
    baseStock: {
      diesel_parts: 50,
      tools: 60,
      pump_shotgun_12g: 6,
      grease_smg_9mm: 6,
      carbine_556: 3,
      sniper_rifle_762: 2,
      peacemaker_45: 3,
      ammo_9mm: 110,
      ammo_12g: 85,
      ammo_45: 50,
      ammo_556: 50,
      ammo_762: 35,
      field_bandage: 45,
      antibiotics: 25,
      gasoline: 35,
      water: 50,
      food_rations: 35,
    },
    strictContrabandCheck: true,
    npcs: {
      general_trader: {
        role: "general_trader",
        name: "Alderman Cornelius Pullman",
        title: "Great Lakes Rail & Foundry Consortium",
        greeting:
          "Welcome to the Steel City, caravan boss! Our foundry workers are hungry for Tombstone Canned Beef and thirsty for Frontier Whiskey, and our furnaces devour Leadville Copper Ore. Load up on Precision Engine Parts for your trip west!",
        loreDialogue:
          "New Chicago keeps the engines of the post-collapse United States turning. Every piston and injector at Blackwater Rig was milled right here in our South Side works.",
        tipDialogue:
          "Buy Precision Engine Parts here at 0.56x price and haul them to Blackwater Rig where they sell for 1.65x!",
      },
      transport_master: {
        role: "transport_master",
        name: "Chief Mechanic Radek Kowalski",
        title: "Union Locomotive & Motor Yard",
        greeting:
          "Whether you need an armored V8 Cargo Truck for bulk steel runs or a V6 Interceptor Buggy to tear across the alkali flats, our union mechanics build 'em bulletproof.",
        loreDialogue:
          "Keep an eye on your payload ratio — overloading any transport past 70% capacity starts trimming your cruising speed.",
        tipDialogue:
          "A New Denver V8 Cargo Truck (1,200 kg) lets you haul entire foundry shipments of Copper Ore and Canned Beef in a single trip.",
      },
      sheriff: {
        role: "sheriff",
        name: "Inspector Eliot Ness",
        title: "Untouchables Customs & Rail Bureau",
        greeting:
          "Legal Oak Whiskey casks are welcome in New Chicago, trader, but if my agents catch you smuggling Leadville Canyon Moonshine through the rail viaduct, we confiscate every jug and fine you hard.",
        loreDialogue:
          "Highway syndicates between Saint Louis and New Chicago pack 9mm Grease Guns and Trench Shotguns. Bring real firepower.",
        tipDialogue:
          "The Trench 12G Pump Shotgun and M3 Grease Gun are manufactured right here in New Chicago at a 25% discount.",
      },
      saloon_barkeep: {
        role: "saloon_barkeep",
        name: "Frankie 'The Cap' Torrio",
        title: "The Green Mill Speakeasy",
        greeting:
          "Step out of the lake wind, pal. Down here in the Green Mill, jazz is playing, union bosses are talking market shortages, and my associates pay double for untaxed Canyon Moonshine.",
        loreDialogue:
          "Viktor Kovacs sits in the corner booth — best 7.62mm sniper in the Midwest if you're heading into level-4 danger zones.",
        tipDialogue:
          "Hiring a top-tier marksman makes hunting high-reward highway warlords much safer.",
      },
    },
  },
};

export const ROUTES: RouteEdge[] = [
  {
    id: "route_dust_deadwood",
    from: "dust_creek",
    to: "deadwood_gulch",
    distanceKm: 42,
    terrain: "scorched_flats",
    dangerLevel: 1,
    routeLabel: "North Scrub Trail",
  },
  {
    id: "route_dust_tombstone",
    from: "dust_creek",
    to: "tombstone_crossing",
    distanceKm: 46,
    terrain: "scorched_flats",
    dangerLevel: 1,
    routeLabel: "Mesquite Cattle Trail",
  },
  {
    id: "route_dust_leadville",
    from: "dust_creek",
    to: "leadville_shaft",
    distanceKm: 54,
    terrain: "rocky_canyon",
    dangerLevel: 2,
    routeLabel: "Copper Canyon Pass",
  },
  {
    id: "route_deadwood_leadville",
    from: "deadwood_gulch",
    to: "leadville_shaft",
    distanceKm: 48,
    terrain: "rocky_canyon",
    dangerLevel: 2,
    routeLabel: "Red Gorge Trail",
  },
  {
    id: "route_tombstone_leadville",
    from: "tombstone_crossing",
    to: "leadville_shaft",
    distanceKm: 52,
    terrain: "rocky_canyon",
    dangerLevel: 2,
    routeLabel: "Silver Spur Pass",
  },
  {
    id: "route_deadwood_blackwater",
    from: "deadwood_gulch",
    to: "blackwater_rig",
    distanceKm: 50,
    terrain: "sand_dunes",
    dangerLevel: 3,
    routeLabel: "Alkali Salt Flats",
  },
  {
    id: "route_leadville_blackwater",
    from: "leadville_shaft",
    to: "blackwater_rig",
    distanceKm: 58,
    terrain: "sand_dunes",
    dangerLevel: 3,
    routeLabel: "Sunfire Dune Track",
  },
  {
    id: "route_leadville_stlouis",
    from: "leadville_shaft",
    to: "saint_louis",
    distanceKm: 64,
    terrain: "old_highway",
    dangerLevel: 3,
    routeLabel: "Old Route 66 East",
  },
  {
    id: "route_tombstone_newchicago",
    from: "tombstone_crossing",
    to: "new_chicago",
    distanceKm: 74,
    terrain: "old_highway",
    dangerLevel: 3,
    routeLabel: "Southern Trunk Railway",
  },
  {
    id: "route_leadville_newchicago",
    from: "leadville_shaft",
    to: "new_chicago",
    distanceKm: 66,
    terrain: "old_highway",
    dangerLevel: 3,
    routeLabel: "Cinder Rail Corridor",
  },
  {
    id: "route_blackwater_stlouis",
    from: "blackwater_rig",
    to: "saint_louis",
    distanceKm: 62,
    terrain: "old_highway",
    dangerLevel: 3,
    routeLabel: "Refinery Turnpike",
  },
  {
    id: "route_blackwater_newdenver",
    from: "blackwater_rig",
    to: "new_denver",
    distanceKm: 46,
    terrain: "old_highway",
    dangerLevel: 4,
    routeLabel: "Interstate 70 North",
  },
  {
    id: "route_stlouis_newdenver",
    from: "saint_louis",
    to: "new_denver",
    distanceKm: 68,
    terrain: "old_highway",
    dangerLevel: 4,
    routeLabel: "High Plains Expressway",
  },
  {
    id: "route_stlouis_newchicago",
    from: "saint_louis",
    to: "new_chicago",
    distanceKm: 56,
    terrain: "old_highway",
    dangerLevel: 4,
    routeLabel: "Illinois River Viaduct",
  },
];

export const INITIAL_MARKET_EVENTS: MarketEvent[] = [
  {
    id: "evt_deadwood_drought",
    title: "Brackish Well Crisis in Deadwood Gulch",
    description:
      "The main cattle well in Deadwood Gulch turned alkaline. Ranchers are paying 2.4x normal price for Purified Water!",
    settlementId: "deadwood_gulch",
    affectedItem: "water",
    priceMultiplier: 2.4,
    daysRemaining: 8,
  },
  {
    id: "evt_leadville_fever",
    title: "Shaft Fever Outbreak in Leadville",
    description:
      "Damp tunnel air triggered a lung fever among miners. Leadville Shaft is paying 2.2x for Pre-War Antibiotics!",
    settlementId: "leadville_shaft",
    affectedItem: "antibiotics",
    priceMultiplier: 2.2,
    daysRemaining: 10,
  },
  {
    id: "evt_newdenver_convoy",
    title: "New Denver Patrol Convoy Mobilization",
    description:
      "The Citadel is fueling an expeditionary convoy. Refined Gasoline sells for 1.9x extra in New Denver!",
    settlementId: "new_denver",
    affectedItem: "gasoline",
    priceMultiplier: 1.9,
    daysRemaining: 9,
  },
  {
    id: "evt_tombstone_salt",
    title: "Autumn Cattle Drive in Tombstone Crossing",
    description:
      "Thousands of longhorns arrived at the crossing. Packing houses are paying 2.3x for Desert Salt to cure beef and hides!",
    settlementId: "tombstone_crossing",
    affectedItem: "salt",
    priceMultiplier: 2.3,
    daysRemaining: 9,
  },
  {
    id: "evt_newchicago_copper",
    title: "New Chicago Dynamo Rewiring Project",
    description:
      "The Rail Consortium is rebuilding its lakeside turbines. Smelted Copper Ore fetches 2.1x normal price in New Chicago!",
    settlementId: "new_chicago",
    affectedItem: "copper_ore",
    priceMultiplier: 2.1,
    daysRemaining: 11,
  },
];

export const INITIAL_BOUNTIES: BountyContract[] = [
  {
    id: "bounty_one_eyed_pike",
    bossName: "One-Eyed Pike",
    gangName: "Scrubland Jackals",
    routeId: "route_dust_deadwood",
    originSettlement: "dust_creek",
    rewardCash: 320,
    difficulty: 1,
    description:
      "Pike and his two cutthroats have been robbing water peddlers between Dust Creek and Deadwood Gulch.",
    completed: false,
  },
  {
    id: "bounty_el_coyote",
    bossName: "Mateo 'El Coyote' Garza",
    gangName: "Mesquite Vaquero Outlaws",
    routeId: "route_dust_tombstone",
    originSettlement: "tombstone_crossing",
    rewardCash: 380,
    difficulty: 2,
    description:
      "Cattle rustler ambushing beef and leather carts along the Mesquite Cattle Trail.",
    completed: false,
  },
  {
    id: "bounty_iron_madam",
    bossName: "Madeline 'Slag' Korvex",
    gangName: "Canyon Dynamiters",
    routeId: "route_deadwood_leadville",
    originSettlement: "leadville_shaft",
    rewardCash: 480,
    difficulty: 2,
    description:
      "Former quarry blaster ambushing leather and ammo wagons along Red Gorge Trail.",
    completed: false,
  },
  {
    id: "bounty_diesel_kane",
    bossName: "Warlord Diesel Kane",
    gangName: "Asphalt Reavers",
    routeId: "route_blackwater_newdenver",
    originSettlement: "new_denver",
    rewardCash: 750,
    difficulty: 4,
    description:
      "Heavily armed highway warlord hijacking gasoline shipments on Interstate 70 North.",
    completed: false,
  },
  {
    id: "bounty_capone_ralph",
    bossName: " Frankie 'Chopper' Malone",
    gangName: "Viaduct Iron Syndicate",
    routeId: "route_stlouis_newchicago",
    originSettlement: "new_chicago",
    rewardCash: 820,
    difficulty: 4,
    description:
      "Rogue rail-yard gunmen armed with 9mm Grease Guns extorting convoys on the Illinois River Viaduct.",
    completed: false,
  },
];

export const AVAILABLE_MERCENARIES: Mercenary[] = [
  {
    id: "merc_cassidy",
    name: "Cole 'Deadeye' Cassidy",
    roleTitle: "Ex-Frontier Rifleman",
    homeSettlement: "dust_creek",
    hiringFee: 180,
    dailyWage: 18,
    maxHp: 85,
    hp: 85,
    maxAp: 7,
    accuracyBonus: 14,
    equippedWeapon: "revolver_38",
    bio: "Veteran trail scout who never panics under fire. Quick on the draw with his .38 revolver.",
  },
  {
    id: "merc_hannah",
    name: "Hannah 'Buckshot' McGraw",
    roleTitle: "Gulch Coach Guard",
    homeSettlement: "deadwood_gulch",
    hiringFee: 260,
    dailyWage: 24,
    maxHp: 105,
    hp: 105,
    maxAp: 7,
    accuracyBonus: 12,
    equippedWeapon: "coach_shotgun_12g",
    bio: "Ranch enforcer armed with a double-barrel 12-gauge. Shreds anyone who gets near the wagon.",
  },
  {
    id: "merc_django",
    name: "Django 'Six-Shooter' Morales",
    roleTitle: "Tombstone Pistolero",
    homeSettlement: "tombstone_crossing",
    hiringFee: 320,
    dailyWage: 28,
    maxHp: 98,
    hp: 98,
    maxAp: 8,
    accuracyBonus: 18,
    equippedWeapon: "peacemaker_45",
    bio: "Former Tombstone Ranger who fans a Colt .45 Peacemaker with lethal precision and high AP.",
  },
  {
    id: "merc_vance",
    name: "Sgt. Julian Vance",
    roleTitle: "Saint Louis Deserter Marksman",
    homeSettlement: "saint_louis",
    hiringFee: 420,
    dailyWage: 35,
    maxHp: 110,
    hp: 110,
    maxAp: 8,
    accuracyBonus: 20,
    equippedWeapon: "carbine_556",
    bio: "Trained in Saint Louis urban warfare. Carries a 5.56 Carbine and high AP mobility.",
  },
  {
    id: "merc_kovacs",
    name: "Viktor 'Longshot' Kovacs",
    roleTitle: "New Chicago Rail Sniper",
    homeSettlement: "new_chicago",
    hiringFee: 560,
    dailyWage: 44,
    maxHp: 115,
    hp: 115,
    maxAp: 8,
    accuracyBonus: 25,
    equippedWeapon: "sniper_rifle_762",
    bio: "Elite sharpshooter from the Great Lakes rail garrisons. Wields an M24 7.62mm Sniper Rifle capable of cross-map headshots.",
  },
];

export const SECRET_LOCATIONS: SecretLocation[] = [
  {
    id: "abandoned_mine",
    name: "Old Uranium Prospect Mine",
    x: 520,
    y: 180,
    description: "A forgotten tunnel containing smelted ingots and mechanical tools.",
    lootItems: { scrap_metal: 8, tools: 2 },
    lootCash: 150,
  },
  {
    id: "canyon_cache",
    name: "Smuggler's Canyon Cache",
    x: 480,
    y: 440,
    description: "A hidden crate concealed under desert brush with rifle ammo and a weapon.",
    lootItems: { ammo_308: 20, bolt_rifle_308: 1 },
    lootCash: 200,
  },
  {
    id: "radioactive_oasis",
    name: "Sunken Chemical Cistern",
    x: 720,
    y: 260,
    description: "Filtered cistern reservoirs preserving clean water and pre-war medical supplies.",
    lootItems: { water: 12, antibiotics: 3 },
    lootCash: 90,
  },
  {
    id: "military_compound",
    name: "Acampamento Militar Blindado",
    x: 895,
    y: 385,
    description: "Base militar fortificada nos arredores da capital contendo fuzis 5.56, munição 7.62 e peças a diesel.",
    lootItems: { carbine_556: 1, ammo_556: 30, ammo_762: 15, diesel_parts: 2 },
    lootCash: 450,
  },
];

export const INITIAL_ROVING_ENTITIES: RovingEntity[] = [
  // 1. MERCADORES (Estrada & Fora da Estrada)
  {
    id: "caravan_red_rock",
    name: "Caravana Mercante Red Rock",
    type: "trader",
    x: 185,
    y: 455,
    targetX: 330,
    targetY: 230,
    speedKmh: 6.2,
    heading: 38,
    transportLabel: "Carroça Pesada & Mulas",
    routeMode: "road",
    partySize: 5,
    description: "Comboio comercial bem escoltado transportando grãos, couro curado e ferramentas pela estrada.",
  },
  {
    id: "caravan_water_guild",
    name: "Comboio de Água de Dust Creek",
    type: "trader",
    x: 165,
    y: 495,
    targetX: 300,
    targetY: 620,
    speedKmh: 5.8,
    heading: 132,
    transportLabel: "Parelha de Mulas",
    routeMode: "road",
    partySize: 4,
    description: "Mercadores de água potável descendo a trilha rumo aos currais de Tombstone Crossing.",
  },
  {
    id: "caravan_chicago_express",
    name: "Expresso Diesel de Nova Chicago",
    type: "trader",
    x: 815,
    y: 540,
    targetX: 880,
    targetY: 650,
    speedKmh: 14.2,
    heading: 150,
    transportLabel: "Caminhão de Carga V8",
    routeMode: "road",
    partySize: 6,
    description: "Comboio motorizado pesado transportando peças a diesel e antibióticos entre as metrópoles do Leste.",
  },
  {
    id: "caravan_dune_nomads",
    name: "Mercadores Nômades das Dunas",
    type: "trader",
    x: 420,
    y: 280,
    targetX: 590,
    targetY: 240,
    speedKmh: 7.0,
    heading: 78,
    transportLabel: "Besta de Carga do Deserto",
    routeMode: "offroad",
    partySize: 4,
    description: "Comerciantes livres que cortam caminho fora das estradas principais para evitar pedágios.",
  },

  // 2. PESSOAS VIAJANDO / VIAJANTES (Estrada & Fora da Estrada)
  {
    id: "travelers_dust_pilgrims",
    name: "Viajantes de Dust Creek",
    type: "traveler",
    x: 158,
    y: 468,
    targetX: 330,
    targetY: 230,
    speedKmh: 4.8,
    heading: 36,
    transportLabel: "A Pé & Burro de Carga",
    routeMode: "road",
    partySize: 3,
    description: "Grupo de trabalhadores e colonos caminhando pela trilha inicial com um burro de carga.",
  },
  {
    id: "travelers_settler_wagon",
    name: "Família de Colonos da Fronteira",
    type: "traveler",
    x: 315,
    y: 310,
    targetX: 300,
    targetY: 620,
    speedKmh: 5.5,
    heading: 183,
    transportLabel: "Carroça Leve de Madeira",
    routeMode: "road",
    partySize: 4,
    description: "Família viajando pela fronteira oeste com seus pertences e suprimentos básicos.",
  },
  {
    id: "travelers_lone_prospector",
    name: "Garimpeiro Solitário",
    type: "traveler",
    x: 245,
    y: 495,
    targetX: 520,
    targetY: 540,
    speedKmh: 5.2,
    heading: 99,
    transportLabel: "Mula de Garimpo",
    routeMode: "offroad",
    partySize: 1,
    description: "Explorador veterano atravessando o terreno aberto fora da trilha em direção às minas.",
  },
  {
    id: "travelers_courier_rider",
    name: "Mensageiro da Fronteira",
    type: "traveler",
    x: 510,
    y: 370,
    targetX: 800,
    targetY: 520,
    speedKmh: 9.8,
    heading: 117,
    transportLabel: "Cavalo de Sela Rápido",
    routeMode: "offroad",
    partySize: 1,
    description: "Cavaleiro solitário cortando caminho pelo deserto aberto levando cartas e encomendas urgentes.",
  },

  // 3. POLICIAIS / PATRULHAS DA LEI (SEMPRE a Cavalo ou de Carro, na estrada e fora dela)
  {
    id: "patrol_county_sheriff",
    name: "Patrulha Montada da Polícia",
    type: "sheriff_patrol",
    x: 195,
    y: 445,
    targetX: 140,
    targetY: 480,
    speedKmh: 10.5,
    heading: 247,
    transportLabel: "Cavalos de Guerra",
    routeMode: "road",
    partySize: 4,
    description: "Policiais montados a cavalo patrulhando as rotas iniciais da fronteira contra saqueadores.",
  },
  {
    id: "patrol_highway_interceptor",
    name: "Esquadrão Policial Motorizado",
    type: "sheriff_patrol",
    x: 740,
    y: 390,
    targetX: 860,
    targetY: 160,
    speedKmh: 15.2,
    heading: 27,
    transportLabel: "Viatura Policial V8",
    routeMode: "road",
    partySize: 4,
    description: "Unidade policial em carros V8 interceptores mantendo a ordem nas rodovias entre Saint Louis e a Capital.",
  },
  {
    id: "patrol_canyon_rangers",
    name: "Rangers Policiais do Cânion",
    type: "sheriff_patrol",
    x: 450,
    y: 465,
    targetX: 520,
    targetY: 540,
    speedKmh: 10.8,
    heading: 130,
    transportLabel: "Cavalos de Patrulha",
    routeMode: "offroad",
    partySize: 3,
    description: "Destacamento policial a cavalo vasculhando os cânions fora da estrada atrás de esconderijos de foras-da-lei.",
  },

  // 4. BANDIDOS / SAQUEADORES DIVIDIDOS POR ZONA DE NÍVEL (Nv.1 Animais -> Nv.4 Carros & Caminhões)
  {
    id: "raiders_dust_scavengers",
    name: "Saqueadores de Burro da Poeira (Nv. 1)",
    type: "raider",
    x: 185,
    y: 435,
    targetX: 140,
    targetY: 480,
    speedKmh: 5.4,
    heading: 225,
    transportLabel: "Burros & Mulas de Carga",
    routeMode: "offroad",
    partySize: 3,
    description: "Bandidos fracos da área inicial limitados a burros e mulas de carga, armados apenas com facões e garruchas .22.",
  },
  {
    id: "raiders_scrub_drifters",
    name: "Ladrões de Gado de Tombstone (Nv. 1)",
    type: "raider",
    x: 240,
    y: 545,
    targetX: 300,
    targetY: 620,
    speedKmh: 5.8,
    heading: 141,
    transportLabel: "Mulas Velhas de Trilha",
    routeMode: "road",
    partySize: 3,
    description: "Pequeno bando maltrapilho da fronteira inicial se deslocando com animais lentos e armas improvisadas.",
  },
  {
    id: "raiders_canyon_bushwhackers",
    name: "Emboscadores do Desfiladeiro (Nv. 2)",
    type: "raider",
    x: 470,
    y: 490,
    targetX: 520,
    targetY: 540,
    speedKmh: 7.8,
    heading: 135,
    transportLabel: "Cavalos & Carroça Leve",
    routeMode: "offroad",
    partySize: 3,
    description: "Bandidos de nível médio montados a cavalo rondando as encostas rochosas com carabinas .38 e escopetas.",
  },
  {
    id: "raiders_asphalt_jackals",
    name: "Piratas Motorizados Chacal (Nv. 3)",
    type: "raider",
    x: 710,
    y: 440,
    targetX: 800,
    targetY: 520,
    speedKmh: 12.6,
    heading: 132,
    transportLabel: "Carros de Assalto V8",
    routeMode: "road",
    partySize: 4,
    description: "Quadrilha motorizada em carros V8 adaptados com chapas de aço caçando caravanas nas estradas do Leste.",
  },
  {
    id: "raiders_military_renegades",
    name: "Renegados do Acampamento Militar (Nv. 4)",
    type: "raider",
    x: 855,
    y: 395,
    targetX: 880,
    targetY: 650,
    speedKmh: 15.2,
    transportLabel: "Caminhões & Carros Blindados V8",
    heading: 174,
    routeMode: "offroad",
    partySize: 4,
    description: "Esquadrão fortemente armado da região da Capital e Acampamento Militar, operando carros e caminhões V8 com fuzis 5.56 e snipers 7.62.",
  },
];

export function createInitialGameState(): GameState {
  const initialTownStocks: Record<SettlementId, Partial<Record<ItemId, number>>> = {
    dust_creek: { ...SETTLEMENTS.dust_creek.baseStock },
    deadwood_gulch: { ...SETTLEMENTS.deadwood_gulch.baseStock },
    leadville_shaft: { ...SETTLEMENTS.leadville_shaft.baseStock },
    blackwater_rig: { ...SETTLEMENTS.blackwater_rig.baseStock },
    tombstone_crossing: { ...SETTLEMENTS.tombstone_crossing.baseStock },
    saint_louis: { ...SETTLEMENTS.saint_louis.baseStock },
    new_denver: { ...SETTLEMENTS.new_denver.baseStock },
    new_chicago: { ...SETTLEMENTS.new_chicago.baseStock },
  };

  return {
    saveVersion: 3,
    weaponMagazines: {},
    exploration: { x: 140, y: 480, heading: 0, isMoving: false, isPaused: true, terrain: "scorched_flats", distanceTravelledKm: 0 },
    playerName: "Arthur Morgan Jr.",
    attributes: {
      grit: 4,
      agility: 5,
      perception: 5,
      charisma: 4,
    },
    unspentAttributePoints: 3, // Player gets 3 bonus points to customize their build!
    hp: 98, // 50 + 4 * 12
    maxHp: 98,
    equippedWeapon: "bolt_rifle_308",
    cash: 1000, // Grandfather's $1,000 inheritance
    day: 1,
    hour: 8,
    currentSettlement: "dust_creek",
    lastVisitedSettlement: "dust_creek",
    transport: "old_donkey", // Grandfather's Pack Donkey
    ownedTransports: ["on_foot", "old_donkey"],
    activeFleet: { old_donkey: 1 },
    vehicleCondition: 100,
    isBrokenDown: false,
    freightContracts: [],
    passengerContracts: [],
    rovingEntities: [...INITIAL_ROVING_ENTITIES],
    discoveredSecretIds: [],
    clearedSecretIds: [],
    inventory: {
      bolt_rifle_308: 1, // Grandfather's old rifle
      rusty_machete: 1, // Backup melee blade
      ammo_308: 12, // Some .308 bullets
      water: 10, // Starting water
      food_rations: 8, // Starting food
      animal_forage: 8, // Starting donkey forage
      field_bandage: 2,
    },
    townStocks: initialTownStocks,
    marketEvents: [...INITIAL_MARKET_EVENTS],
    knownRumorIds: ["evt_deadwood_drought"],
    bounties: [...INITIAL_BOUNTIES],
    hiredMercenaries: [],
    travelState: null,
    pendingEncounter: null,
    combatState: null,
    reputation: 10,
    journalLogs: [
      "Day 1, 08:00 — You buried your grandfather on the ridge overlooking Dust Creek. His inheritance is yours: $1,000 in Trade Guild script, his faithful pack donkey, an old .308 bolt-action rifle with 12 brass rounds, and a rusty machete.",
      "Tip: Allocate your 3 unspent Attribute Points in the Character panel, buy cheap Water & Forage in Dust Creek, and head to Deadwood Gulch or Tombstone Crossing to start your merchant route!",
    ],
  };
}
